from django.conf.urls import patterns, url



from twipymap2.views.user_views import *
urlpatterns = patterns('',
    url(
        regex=r'^user/archive/$',
        view=UserArchiveIndexView.as_view(),
        name='twipymap2_user_archive_index'
    ),
    url(
        regex=r'^user/create/$',
        view=UserCreateView.as_view(),
        name='twipymap2_user_create'
    ),
    url(
        regex=r'^user/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=UserDateDetailView.as_view(),
        name='twipymap2_user_date_detail'
    ),
    url(
        regex=r'^user/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=UserDayArchiveView.as_view(),
        name='twipymap2_user_day_archive'
    ),
    url(
        regex=r'^user/(?P<pk>\d+?)/delete/$',
        view=UserDeleteView.as_view(),
        name='twipymap2_user_delete'
    ),
    url(
        regex=r'^user/(?P<pk>\d+?)/$',
        view=UserDetailView.as_view(),
        name='twipymap2_user_detail'
    ),
    url(
        regex=r'^user/$',
        view=UserListView.as_view(),
        name='twipymap2_user_list'
    ),
    url(
        regex=r'^user/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=UserMonthArchiveView.as_view(),
        name='twipymap2_user_month_archive'
    ),
    url(
        regex=r'^user/today/$',
        view=UserTodayArchiveView.as_view(),
        name='twipymap2_user_today_archive'
    ),
    url(
        regex=r'^user/(?P<pk>\d+?)/update/$',
        view=UserUpdateView.as_view(),
        name='twipymap2_user_update'
    ),
    url(
        regex=r'^user/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=UserWeekArchiveView.as_view(),
        name='twipymap2_user_week_archive'
    ),
    url(
        regex=r'^user/archive/(?P<year>\d{4})/$',
        view=UserYearArchiveView.as_view(),
        name='twipymap2_user_year_archive'
    ),
)


from twipymap2.views.contact_views import *
urlpatterns += patterns('',
    url(
        regex=r'^contact/archive/$',
        view=ContactArchiveIndexView.as_view(),
        name='twipymap2_contact_archive_index'
    ),
    url(
        regex=r'^contact/create/$',
        view=ContactCreateView.as_view(),
        name='twipymap2_contact_create'
    ),
    url(
        regex=r'^contact/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/'
               '(?P<pk>\d+?)/$',
        view=ContactDateDetailView.as_view(),
        name='twipymap2_contact_date_detail'
    ),
    url(
        regex=r'^contact/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               '(?P<day>\d{1,2})/$',
        view=ContactDayArchiveView.as_view(),
        name='twipymap2_contact_day_archive'
    ),
    url(
        regex=r'^contact/(?P<pk>\d+?)/delete/$',
        view=ContactDeleteView.as_view(),
        name='twipymap2_contact_delete'
    ),
    url(
        regex=r'^contact/(?P<pk>\d+?)/$',
        view=ContactDetailView.as_view(),
        name='twipymap2_contact_detail'
    ),
    url(
        regex=r'^contact/$',
        view=ContactListView.as_view(),
        name='twipymap2_contact_list'
    ),
    url(
        regex=r'^contact/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/$',
        view=ContactMonthArchiveView.as_view(),
        name='twipymap2_contact_month_archive'
    ),
    url(
        regex=r'^contact/today/$',
        view=ContactTodayArchiveView.as_view(),
        name='twipymap2_contact_today_archive'
    ),
    url(
        regex=r'^contact/(?P<pk>\d+?)/update/$',
        view=ContactUpdateView.as_view(),
        name='twipymap2_contact_update'
    ),
    url(
        regex=r'^contact/archive/(?P<year>\d{4})/'
               '(?P<month>\d{1,2})/'
               'week/(?P<week>\d{1,2})/$',
        view=ContactWeekArchiveView.as_view(),
        name='twipymap2_contact_week_archive'
    ),
    url(
        regex=r'^contact/archive/(?P<year>\d{4})/$',
        view=ContactYearArchiveView.as_view(),
        name='twipymap2_contact_year_archive'
    ),
)
